clojure/clojurescript-site

content/about/differences.adoc
Catch up with latest language features as documented on the original Wiki prior to the creation of the ClojureScript site.
=> Update "Differences" page namespaces section

content/community/companies.adoc
The intros.io site has for a while now been rebranded as jobs.functionalworks.com
(I have a signed contributor agreement)
=> Update FunctionalWorks link

content/guides/quick-start.adoc
(Missed one of the two links in the previous PR.)
=> Update QuickStart link to released 1.9.216 JAR

content/reference/dependencies.adoc
Missing Javascript type in source-highlight causing a bug on the dependencies section. Tests for chrome and firefox.
=> Fix bug onMouseOver event in source-highlight box

content/guides/custom-repls.adoc
I'm not sure if second link to points to the right line (https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/repl/node.clj#L69)
=> Fix links in guides/custom-repls

content/tools/light-table.adoc
Move the [link title] behind the link to display it correctly
=> Adjust links to lighttable and full tutorial

content/community/building.adoc
(Previously, this document was hosted in the GitHub repo, and used "_this_ repository" language.)
=> Link to the GitHub repo

content/guides/javascript-modules.adoc
When running through the `(require '[js.hello :as hello] :reload)` example, I got an error message from Node:
> SyntaxError: Identifier 'sayHello$$module$src$js$hello' has already been declared
>     at /home/rei/repos/hello-es6/.cljs_node_repl/src/js/hello.js:1:1
>     at ContextifyScript.Script.runInThisContext (vm.js:26:33)
>     at Object.exports.runInThisContext (vm.js:79:17)
>     at nodeGlobalRequire (repl:85:6)
>     at global.CLOSURE_IMPORT_SCRIPT (repl:75:3)
>     at Object.goog.require (repl:21:8)
>     at repl:1:6
>     at ContextifyScript.Script.runInThisContext (vm.js:26:33)
>     at Object.exports.runInThisContext (vm.js:79:17)
>     at Domain.<anonymous> ([stdin]:50:34)
This was due to the fact that Node (my version is 7.4.0) disallows redefinining anything declared with a …
=> Replace `export let` with `export var`

content/reference/google-closure-library.adoc
fixes #53
original text: https://github.com/clojure/clojurescript/wiki/Google-Closure-Library#searching-for-examples
=> Add Closure Library search examples as per the wiki

content/community/companies.adoc
Liveops Cloud has rebranded to Serenova (but we still use ClojureScript)
=> Change Liveops Cloud to Serenova

content/reference/bootstrapping.adoc
- Remove broken link for SessionRepl - I couldn't find anything that made sense to replace it with on Google, though it may be out there
- Add Lumo, Klipse, and Klangmeister (these existed on the Github wiki but not here)
=> Update "Bootstrapping the Compiler" page

content/guides/quick-start.adoc
Explicit notice that `rlwrap` is not required
Also `brew install rlwrap` is broken
=> Update 'rlwarp' usage necessity in QuickStart site

.gitignore, content/guides/quick-start.adoc
ASCIIDoc does not provide a mechanism for adding the `rel` attribute to links. As a workaround, I used the passthrough syntax to add the [proper link relation](https://www.iana.org/assignments/link-relations/link-relations.xhtml).
The link itself points to the latest release page at GitHub. You can make the link dynamic as described in #23  by adding a snippet of JavaScript to the `footer.ftl` file in the current theme assets:
```
<script>
$(document).ready(function() {
$.getJSON("https://api.github.com/repos/clojure/clojurescript/releases/latest").done(function(release) {var asset = release.assets[0].browser_download_url; $("a[rel='latest-version']").attr("href", asset)}) });
</script>
```
=> Auto-link Quick Start to latest release

content/reference/compiler-options.adoc
Includes `:protocol-impl-recur-with-target`, which is slated for the next release
=> Update list of compiler warnings

content/community/companies.adoc
Proposing this change to the companies page. Workframe uses a full-stack Clojure stack. We are naced in NYC and I am the CTO and one of the founders.
=> Adds Workframe to companies list

content/reference/compiler-options.adoc
Ref https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/closure.clj#L257 and https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/closure.clj#L171
Found this by reading the closure.clj source as needed to output a ISO-8859-1 file instead of Unicode for loading compiled JavaScript into LDAP.
=> Add :closure-output-charset

content/reference/compiler-options.adoc
Also, since these default to off, use this as an opportunity to illustrate how to enable a warning.
This change should not be merged until the next compiler is released (these are currently in master).
=> Add :checked-arrays and :invalid-array-access

content/tools/atom.adoc
* Parinfer link fixed to point to the Parinfer project page
* A little more explanation on installing Joker linter
* Fixing backtick typo before the word "piggieback"
=> Wording/typo fixes for the Atom tools page

content/reference/compiler-options.adoc
It used to install, but the `:install-deps` flag controls that.
=> Eliminate language implying `:npm-deps` installs

content/reference/compiler-options.adoc
* Add an extra dash to indicate code
* Just provide the key and value like other examples
=> Fix formatting of NPM deps example

content/reference/compiler-options.adoc
=> Fix typo in :foreign-libs example

content/reference/compiler-options.adoc
Note that `:main` must be provided for `:preloads` and `:closure-defines` to work when doing an `:optimizations :none` build.
=> Add note for preloads and closure-defines compiler options

content/reference/compiler-options.adoc
Relevant compiler source: https://github.com/clojure/clojurescript/blob/2389e52049a9bd001d173a1cb4772ed8a25de196/src/main/clojure/cljs/closure.clj#L408-L411
=> Clarify when :foreign-libs :file-min is used

content/guides/javascript-modules.adoc
The project doesn't build if you use version stated in the guide. With this newer version it all works.
https://github.com/clojure/clojurescript-site/issues/143
=> newer Clojurescript version

content/news/2018-03-26-clojurescript-command-line.adoc
I was baffled at first when I read the set up steps ("deps.edn?").
Also I'd recommend to stick to one approach at a time: either JAR or CLJ - I recommend JAR, to keep things extremely simple for the user. Please let me know if you'd like help with that. It would make the tutorial much simpler.
Using a specific version of the JAR rather than latest - since the `deps.edn` uses a specific one. It's more uniform, clearer. It's also easier to point the user directly to the JAR.
=> 2018-03-26-clojurescript-command-line: Make the set up clearer

content/reference/compiler-options.adoc
- process-shim defaults to false for NodeJS target.
- Modify package-json-resolution default value list a bit, "if no :target is set" is not correct, it is "if :target is not :nodejs"
=> Mention process-shim default for NodeJS

content/guides/code-splitting.adoc
This PR adds `Additional Notes` section, for `Code Splitting` guide, which explains how to prevent possible interference of code splits with other JavaScript defined in the global scope.
=> Mention :rename-prefix compiler option as a way to mitigate polluting global scope

content/reference/javascript-api.adoc
I found it confusing that this described the "JavaScript API" and then all the examples were in ClojureScript.  I also found referring to "ClojureScript types" a little confusing.  Hopefully this conveys the intent.
=> Minor tweak to JavaScript API introduction

content/guides/quick-start.adoc
Incomplete until we have a `https://github.com/clojure/clojurescript/releases/download/r1.10.312/cljs.jar` or a Windows version of Clojure CLI tools.
=> Update QuickStart for 1.10.312

content/about/differences.adoc
Nowadays, most devs don't start a ClojureScript REPL from a Clojure REPL.
Revise copy to simply highlight that ClojureScript is similar to Clojure in providing a REPL-first experience.
=> Update bit about starting REPLs

content/tools/emacs-inf.adoc
run-clojure was an alias for inf-clojure, but it was removed in version 2.0 of inf-clojure. See the last bullet point in the Changes section: https://github.com/clojure-emacs/inf-clojure/releases/tag/v2.0.0
=> Change run-clojure to inf-clojure.

content/guides/faq-js.adoc
In the code samples, they were breaking the syntax highlighting. The text was inconsistent between using “” with "" and ’ with '.
Updated so that everything uses straight quotes, " and '.
=> Remove curly quotes from faq-js.adoc

content/reference/compiler-options.adoc
For https://dev.clojure.org/jira/browse/CLJS-2815
=> CLJS-2815: Global-exports should support strings as keys

content/community/running-tests.adoc
Testing JavaScript Engines under Running the Tests is no longer stale.
Of note: JavaScriptCore setup has been greatly simplified by simpling using
the jsc that is already present on macOS. Thanks @mfikes!
Fixes #310
=> Freshen Running the Tests docs

content/reference/google-closure-library.adoc
as per https://github.com/clojure/clojurescript-site/issues/170
=> Remove link to expired (and now containing malware(?)) domain

content/guides/guides.adoc, content/guides/promise-interop.adoc
This is part of https://clojure.atlassian.net/browse/ASYNC-230 and shouldn't be merged without the corresponding patch to https://github.com/clojure/core.async.
=> Add promise interop page

content/guides/project-templates.adoc
It's not showing up correctly because the link must not include spaces.
Followup to https://github.com/clojure/clojurescript-site/pull/328
=> Fix Shadow CLJS template section link

content/reference/google-closure-library.adoc
The links to Google Closure Library namespaces and classes API docs have changed, update the Google Closure Library document to use the new links.
Add Glögi to the table of wrapper libraries, as an alternative to using goog.log directly.
=> Fix dead links to Closure Library API, add Glögi

content/community/resources.adoc
This PR adds #clojurescript@Clojurians-Zulip to the chat-section.
Also added the searchable slack-archive on Zulip.
(Separate commits to allow for cherry-picking).
=> Add Clojurians-Zulip

content/community/companies.adoc
This is frequently a page that people want to update, so they shouldn't have to go elsewhere to find out how to do it.
=> Add brief instructions on how to add a company to Companies

content/guides/webpack.adoc
main.js was being compiled to 'out/out/main.js'
=> redundant 'out' directory in webpack.config.js

content/guides/webpack.adoc
This is not necessary, as the params we use can be passed from the
webpack CLI.  Webpack is now "zero config".
@dpsutton raised in slack that the webpack.config.js approach should be documented in order for users to progress to more complicated setups.
However, you can create a webpack.config.js without having to add the entry/output parameters back to the webpack.config.js.  The CLI arguments will be combined with those in webpack.config.js, this means you can simply copy/paste from the documentation on the webpack site in order to add complicated parts.
=> Remove unnecessary webpack.config.js from guide

content/reference/bootstrapping.adoc
It's now also rendered incorrectly on the actual site.
=> Fix link to Klangmeister

content/guides/webpack.adoc
I signed the CLA.
This documents what I got working (thanks to help in #clojurescript in the Clojurians Slack) for building webworkers with `:target :bundle`.
=> Add webworker section to webpack guide

content/community/contributing_site.adoc, content/tools/leinigen.adoc, content/tools/shadow-cljs.adoc, content/tools/vscode.adoc
In regards to this issue: https://github.com/clojure/clojurescript-site/issues/387
I added three pages in the tooling section. I think the added tools (vscode and shadow-cljs) warrant mention on the site.
Caveat: The individual pages are small. I specifically didn't use leinigen for ClojureScript for a long time.
To accommodate the changes I suggest to change the navigation like so under `tools.ftl`:
```html
<a href="vscode" class="w-nav-link clj-section-nav-item-link">Visual Studio Code</a>
<div class="w-nav-link clj-section-nav-heading">Build Tools</div>
<a href="leinigen" class="w-nav-link clj-section-nav-item-link">Leinigen</a>
<a href="shadow-cljs" class="w-nav-link clj-section-nav-item-link">shadow-cljs</a>
```
=> Tools section

README.adoc, content/reference/compiler-options.adoc
The ampersand in the compiler-option `global-goog-object&array` prevents the anchor from being rendered correctly:
```
[[:global-goog-object&array]] === :global-goog-object&array
Defaults to false. If true load goog.object and goog.array as global namespaces rather than as goog.module namespaces.
```
=> Fix anchor compiler-option global-goog-object&array

content/reference/compiler-options.adoc
Written as if CLJS-3074 is merged, implying that symbols are resolved to
the appropriate function.
=> Document :warning-handlers

content/tools/tools.adoc
removed link to lein-figwheel as well.
=> Adding figwheel to the build tools

content/community/resources.adoc
Whilst Slack itself is HTTPS, the invite link is HTTP. This reverts the change from July 2021 that broke the invite link by changing it to HTTPS.
=> Revert Slack *invite* link to HTTP

content/community/libraries.adoc
Pointed out on [Slack](https://clojurians.slack.com/archives/CNMR41NKB/p1742270509144139) that the link for uix is wrong
=> Update link for uix
