clojure/clojurescript-site

content/guides/project-templates.adoc
Fixed misspelled word (variants.)
=> Updated project-templates.adoc

content/reference/compiler-options.adoc, content/reference/documentation.adoc, content/reference/javascript-library-preprocessing.adoc, content/reference/javascript-module-support.adoc
=> Adding documentation for JS module support and preprocessing.

content/community/companies.adoc
We are about to deploy our frontend rewritten in CLJS using Re-frame/Reagent. Thanks!
=> Add American Physical Society to the list of companies using CLJS

content/community/companies.adoc
Using ClojureScript on the frontend as well as for parts of the backend.
=> Add Nextjournal to the list of companies using ClojureScript

content/community/companies.adoc
I was curious what a company called butterbutt might do, only to discover it no longer exists ):
=> Remove no longer existing company

content/tools/testing.adoc
#67
- Converted markdown to asciidoc using IntelliJ plugin
- Formatted newlines at col 72
=> Bring testing section up to date with wiki

content/community/reporting-bootstrap-issues.adoc
Addresses https://github.com/clojure/clojurescript-site/issues/66
=> Fix formatting for "reporting bootstrap issues"

content/community/companies.adoc
Added Floating Point company to the list. Authors of Keechma framework.
=> Added Floating Point company to the list

content/community/libraries.adoc
- add line boot-atomizer in CSS generation sections.
=> Add libraries atomizer in CSS Generation

content/about/differences.adoc
- For next release
- Also cleans up ^:const description
=> Update for new semantics of ^:const

content/tools/atom.adoc
Initial draft for adding an Atom editor page, as per Issue #57
=> Issue #57: Adding initial version of Atom editor page to Tools section

content/guides/code-splitting.adoc, content/news/2017-07-10-code-splitting.adoc, content/news/2017-07-14-code-splitting.adoc
=> Draft of code splitting post

content/community/running-tests.adoc
In preparation for https://dev.clojure.org/jira/browse/CLJS-2192
=> Instructions for setting up ChakraCore

content/guides/javascript-modules.adoc
https://dev.clojure.org/jira/browse/CLJS-2193
=> Update the JS modules guide in the context of CLJS-2193

content/reference/advanced-compilation.adoc
=> Document ^:export

content/guides/quick-start.adoc
based on feedback here: https://www.reddit.com/r/Clojure/comments/6q0jhn/why_reframe_instead_of_om_next/dkw11e0/
=> Update CLJSJS React to 15.6.1-0 in quick start

content/guides/code-splitting.adoc, content/news/2017-07-10-code-splitting.adoc
Waiting on the next release of ClojureScript.
=> Update docs for next release

content/reference/advanced-compilation.adoc
Inspired by https://dev.clojure.org/jira/browse/CLJS-2406
=> Add clarifications to renaming under advanced

content/guides/quick-start.adoc
And simplify by removing extra / duplicate verbiage about Java 8.
=> Update to remove outdated Java 7 requirement

content/reference/compiler-options.adoc
because users really need to know where to put them :)
=> :externs searched for in the pwd and classpath

content/guides/ns-forms.adoc
=> ns Forms Guide

content/reference/documentation.adoc, content/reference/javascript-api.adoc
=> Add JavaScript API page

content/guides/guides.adoc, content/guides/ns-forms.adoc
Link the guide on the main page and add a toc
=> ns Forms guide navigation

content/reference/compiler-options.adoc
This has been fixed in lein-cljsbuild for a while
https://github.com/emezeske/lein-cljsbuild/issues/381
=> Remove lein-cljsbuild note

content/reference/compiler-options.adoc
=> Document :infer-externs compiler option

content/reference/compiler-options.adoc
Updates language-in default to match https://dev.clojure.org/jira/browse/CLJS-2389
=> Update language-in/out values and defaults

content/reference/documentation.adoc, content/reference/repl-and-main.adoc
=> Add reference page for cljs.main

content/community/running-tests.adoc
This goes along with https://dev.clojure.org/jira/browse/CLJS-2593
=> Add script/test-cli

content/reference/compiler-options.adoc
=> Add :aot-cache compiler option

content/reference/repl-options.adoc
=> Add browser- and Node- specific repl options

content/reference/compiler-options.adoc
=> Add :stable-names compiler option documentation

content/reference/compiler-options.adoc
=> Document :webworker for :target compiler option

content/guides/quick-start.adoc, content/news/2017-08-16-release.adoc copy
=> Quick start 1.10

content/news/2018-03-26-release.adoc
=> Add missing contributors

content/reference/compiler-options.adoc
For https://github.com/clojure/clojurescript/commit/03455b4ba4338ab05ffccefc9ddb41c8fd128cfa
=> Document :elide-strict compiler option

content/guides/quick-start.adoc
See https://www.merriam-webster.com/dictionary/so-called
=> so called -> so-called

content/about/differences.adoc, content/reference/compiler-options.adoc
For https://dev.clojure.org/jira/browse/CLJS-1702
=> CLJS-1702: Warning when using private vars

content/news/2019-01-31-release.adoc
See https://dev.clojure.org/jira/browse/CLJS-3048
=> Rectify 2019-01-31-release.adoc: [clojure.test.check.properties] needs to be also required.

content/reference/compiler-options.adoc
=> Update :npm-deps documentation

content/community/companies.adoc
Added SquareVenue (squarevenue.com) to list of companies using clojurescript.
=> Add SquareVenue to list of companies using cljs

content/reference/compiler-options.adoc
See https://clojure.atlassian.net/browse/CLJS-2247 and
https://github.com/clojure/clojurescript/commit/cecb9af2b2bf65ddc31e9402496cc8dd1c443d36
Closes #318
=> Document :protocol-with-overwriting-method warning

content/reference/compiler-options.adoc
See https://github.com/clojure/clojurescript/commit/5cc0e6c064132cb3e122177a1a110d5b0d98fceb and
https://clojure.atlassian.net/browse/CLJS-2903
Closes #273
=> Document :fingerprint compiler option

content/community/running-tests.adoc
=> "Don't forget" section under "Running the Tests" has been freshened

content/community/libraries.adoc
Natal hasn't been updated since 2016. re-natal is still active in development.
=> Update libraries.adoc. Added re-natal

content/reference/repl-options.adoc
=> Remove quotes from REPL requires example

content/community/reporting-issues.adoc
=> Section on how to git bisect

content/community/companies.adoc
Add [Freshcode](https://freshcodeit.com/) to the companies list
=> Add Freshcode to companies page

content/about/differences.adoc, content/guides/reader.adoc
guide for Clojurescript Reader, mostly focusing on the differences from Clojure tagged literals.
issue https://github.com/clojure/clojurescript-site/issues/371
=> Clojurescript Reader & data_readers.cljc
